# Generated by Django 4.2.29 on 2026-03-24 18:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_lead_product_interested_lead_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer Inquiry', 'verbose_name_plural': 'Customer Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Food Product', 'verbose_name_plural': 'Food Products'},
        ),
        migrations.AlterField(
            model_name='lead',
            name='company_name',
            field=models.CharField(max_length=150, verbose_name='Company / Restaurant Name'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, help_text='Delivery Location & other notes'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='product_interested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.product', verbose_name='Interested Product (Feed/Oil/Grain)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity Required'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('Qualification', 'Qualification'), ('Proposal', 'Proposal'), ('Negotiation', 'Negotiation'), ('Closed Won', 'Closed Won'), ('Closed Lost', 'Closed Lost')], default='Qualification', max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotelineitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.product', verbose_name='Food Product'),
        ),
    ]
